version: '3.8'

services:
  nginx:
    image: nginx
    container_name: ${DOCKER_PROJECT_NAME}_nginx
    restart: always
    volumes:
      - ./:/var/www/${DOCKER_PROJECT_NAME}
      - ./docker/nginx/:/etc/nginx/conf.d
      - ./storage/docker/logs/nginx/:/var/log/nginx
    ports:
      - ${DOCKER_NGINX_PORT}:80

  php:
    container_name: ${DOCKER_PROJECT_NAME}_php
    restart: always
    build:
      context: docker/php
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: ${DOCKER_PROJECT_NAME}
    user: ${DOCKER_PROJECT_NAME}
    volumes:
      - ./:/var/www/${DOCKER_PROJECT_NAME}
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/z-php.ini
    ports:
      - ${DOCKER_PHP_PORT}:9000

  postgres:
    image: postgres:14
    container_name: ${DOCKER_PROJECT_NAME}_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DOCKER_PROJECT_NAME}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/${DOCKER_PROJECT_NAME}_postgres
    ports:
      - ${DOCKER_POSTGRES_PORT}:5432

  redis:
    image: redis:alpine
    container_name: ${DOCKER_PROJECT_NAME}_redis
    restart: always
    command: redis-server
    volumes:
      - redis:/var/lib/${DOCKER_PROJECT_NAME}_redis
    ports:
      - ${DOCKER_REDIS_PORT}:6379

  meilisearch:
    image: getmeili/meilisearch
    container_name: ${DOCKER_PROJECT_NAME}_meilisearch
    restart: always
    ports:
      - ${DOCKER_MEILISEARCH_PORT}:7700

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: ${DOCKER_PROJECT_NAME}_elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/${DOCKER_PROJECT_NAME}_elasticsearch/data
    ports:
      - ${DOCKER_ELASTICSEARCH_PORT}:9200

  kibana:
    container_name: ${DOCKER_PROJECT_NAME}_kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - ${DOCKER_KIBANA_PORT}:5601

volumes:
  postgres:
    external:
      name: ${DOCKER_PROJECT_NAME}_postgres
  redis:
    external:
      name: ${DOCKER_PROJECT_NAME}_redis
  elasticsearch-data:
    driver: local
